# 임포트 하기  

In [1]:
import pandas as pd
import numpy as np

# 데이터 불러오기 

In [2]:
!pip install openpyxl

In [3]:
girl=pd.read_excel('./data/여자 0-35개월 신장 백분위수.xlsx', engine='openpyxl')

In [4]:
boy=pd.read_excel('./data/남자 0-35개월 신장 백분위수.xlsx', engine='openpyxl')

# 데이터확인 

In [5]:
girl

만나이\n(개월)  신장(cm) 백분위수
0           0         49.1
1           1         53.7
2           2         57.1
3           3         59.8
4           4         62.1
..        ...          ...
67         67        112.1
68         68        112.6
69         69        113.2
70         70        113.7
71         71        114.2

[72 rows x 2 columns]

In [6]:
boy

만나이\n(개월)  신장(cm) 백분위수
0           0         49.9
1           1         54.7
2           2         58.4
3           3         61.4
4           4         63.9
..        ...          ...
67         67        113.3
68         68        113.8
69         69        114.4
70         70        114.9
71         71        115.4

[72 rows x 2 columns]

# 2개 이상의 모든 단의 조합을 생성

In [7]:
sequences = []
for i in range(1, len(boy)):
    sequence =boy.iloc[:i+1,1].values.tolist()
    sequences.append(sequence)

print('학습에 사용할 샘플의 개수: %d' % len(sequences))

학습에 사용할 샘플의 개수: 71


In [8]:
sequences

[[49.9, 54.7],
 [49.9, 54.7, 58.4],
 [49.9, 54.7, 58.4, 61.4],
 [49.9, 54.7, 58.4, 61.4, 63.9],
 [49.9, 54.7, 58.4, 61.4, 63.9, 65.9],
 [49.9, 54.7, 58.4, 61.4, 63.9, 65.9, 67.6],
 [49.9, 54.7, 58.4, 61.4, 63.9, 65.9, 67.6, 69.2],
 [49.9, 54.7, 58.4, 61.4, 63.9, 65.9, 67.6, 69.2, 70.6],
 [49.9, 54.7, 58.4, 61.4, 63.9, 65.9, 67.6, 69.2, 70.6, 72.0],
 [49.9, 54.7, 58.4, 61.4, 63.9, 65.9, 67.6, 69.2, 70.6, 72.0, 73.3],
 [49.9, 54.7, 58.4, 61.4, 63.9, 65.9, 67.6, 69.2, 70.6, 72.0, 73.3, 74.5],
 [49.9,
  54.7,
  58.4,
  61.4,
  63.9,
  65.9,
  67.6,
  69.2,
  70.6,
  72.0,
  73.3,
  74.5,
  75.7],
 [49.9,
  54.7,
  58.4,
  61.4,
  63.9,
  65.9,
  67.6,
  69.2,
  70.6,
  72.0,
  73.3,
  74.5,
  75.7,
  76.9],
 [49.9,
  54.7,
  58.4,
  61.4,
  63.9,
  65.9,
  67.6,
  69.2,
  70.6,
  72.0,
  73.3,
  74.5,
  75.7,
  76.9,
  78.0],
 [49.9,
  54.7,
  58.4,
  61.4,
  63.9,
  65.9,
  67.6,
  69.2,
  70.6,
  72.0,
  73.3,
  74.5,
  75.7,
  76.9,
  78.0,
  79.1],
 [49.9,
  54.7,
  58.4,
  61.4,
  63.

# 모든 샘플에서 길이가 가장 긴 샘플의 길이 출력 

In [9]:
print(max(len(l) for l in sequences))

72


# 입력할 내용을 일정한 길이로 변경 

In [10]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = 72

sequences = pad_sequences(sequences, maxlen=max_len, padding='pre',dtype='float32')

In [11]:
print(sequences)

[[  0.    0.    0.  ...   0.   49.9  54.7]
 [  0.    0.    0.  ...  49.9  54.7  58.4]
 [  0.    0.    0.  ...  54.7  58.4  61.4]
 ...
 [  0.    0.   49.9 ... 113.3 113.8 114.4]
 [  0.   49.9  54.7 ... 113.8 114.4 114.9]
 [ 49.9  54.7  58.4 ... 114.4 114.9 115.4]]


# 특성과 라벨을 분리 

In [12]:
import numpy as np

sequences = np.array(sequences)

X=sequences[:, : -1]
y=sequences[:, -1]

In [13]:
X_train = np.array(X)
y_train = np.array(y)

In [14]:
X_train

array([[  0. ,   0. ,   0. , ...,   0. ,   0. ,  49.9],
       [  0. ,   0. ,   0. , ...,   0. ,  49.9,  54.7],
       [  0. ,   0. ,   0. , ...,  49.9,  54.7,  58.4],
       ...,
       [  0. ,   0. ,  49.9, ..., 112.8, 113.3, 113.8],
       [  0. ,  49.9,  54.7, ..., 113.3, 113.8, 114.4],
       [ 49.9,  54.7,  58.4, ..., 113.8, 114.4, 114.9]], dtype=float32)

In [15]:
X_train = X_train.reshape(71,71,-1)

In [16]:
y_train = y_train.reshape(71,-1)

In [17]:
X_train

array([[[  0. ],
        [  0. ],
        [  0. ],
        ...,
        [  0. ],
        [  0. ],
        [ 49.9]],

       [[  0. ],
        [  0. ],
        [  0. ],
        ...,
        [  0. ],
        [ 49.9],
        [ 54.7]],

       [[  0. ],
        [  0. ],
        [  0. ],
        ...,
        [ 49.9],
        [ 54.7],
        [ 58.4]],

       ...,

       [[  0. ],
        [  0. ],
        [ 49.9],
        ...,
        [112.8],
        [113.3],
        [113.8]],

       [[  0. ],
        [ 49.9],
        [ 54.7],
        ...,
        [113.3],
        [113.8],
        [114.4]],

       [[ 49.9],
        [ 54.7],
        [ 58.4],
        ...,
        [113.8],
        [114.4],
        [114.9]]], dtype=float32)

In [18]:
X_train.shape

(71, 71, 1)

In [19]:
y_train.shape

(71, 1)

# 원 핫 인코딩  

In [20]:
#from tensorflow.keras.utils import to_categorical

#y_en = to_categorical(y, dtype='float32')

In [21]:
#y_en

# RNN예측

In [22]:
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN, LSTM
from tensorflow.keras.models import Sequential

In [23]:
X.shape

(71, 71)

In [24]:
model = Sequential()
model.add(SimpleRNN(64,input_shape = (71,1)))
#model.add(SimpleRNN(32))
#입력 차원 지정(셀 개수 32개), 타임스텝 길이 100, 원핫인코딩 크기 100
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='relu'))
#이진분류 이므로 1개 유닛으 가짓 Dense층 추가

#model.summary() # 전체 구조 출력

In [25]:
model.compile(loss='mse',
    metrics=['mse'],)

In [26]:
history = model.fit(X_train, y_train , epochs=200)

Epoch 1/200
3/3 [==============================] - 1s 5ms/step - loss: 8642.0840 - mse: 8642.0840
Epoch 2/200
3/3 [==============================] - 0s 6ms/step - loss: 8497.7285 - mse: 8497.7285
Epoch 3/200
3/3 [==============================] - 0s 5ms/step - loss: 8383.7285 - mse: 8383.7285
Epoch 4/200
3/3 [==============================] - 0s 5ms/step - loss: 8282.8418 - mse: 8282.8418
Epoch 5/200
3/3 [==============================] - 0s 5ms/step - loss: 8180.9888 - mse: 8180.9888
Epoch 6/200
3/3 [==============================] - 0s 4ms/step - loss: 8089.1494 - mse: 8089.1494
Epoch 7/200
3/3 [==============================] - 0s 5ms/step - loss: 8013.1494 - mse: 8013.1494
Epoch 8/200
3/3 [==============================] - 0s 5ms/step - loss: 7944.0337 - mse: 7944.0337
Epoch 9/200
3/3 [==============================] - 0s 4ms/step - loss: 7877.2700 - mse: 7877.2700
Epoch 10/200
3/3 [==============================] - 0s 5ms/step - loss: 7813.1489 - mse: 7813.1489
Epoch 11/200
3/3 [=

3/3 [==============================] - 0s 4ms/step - loss: 2952.4944 - mse: 2952.4944
Epoch 84/200
3/3 [==============================] - 0s 4ms/step - loss: 2891.4558 - mse: 2891.4558
Epoch 85/200
3/3 [==============================] - 0s 4ms/step - loss: 2833.6689 - mse: 2833.6689
Epoch 86/200
3/3 [==============================] - 0s 4ms/step - loss: 2771.8018 - mse: 2771.8018
Epoch 87/200
3/3 [==============================] - 0s 4ms/step - loss: 2710.4502 - mse: 2710.4502
Epoch 88/200
3/3 [==============================] - 0s 4ms/step - loss: 2650.3267 - mse: 2650.3267
Epoch 89/200
3/3 [==============================] - 0s 4ms/step - loss: 2592.2090 - mse: 2592.2090
Epoch 90/200
3/3 [==============================] - 0s 4ms/step - loss: 2532.2051 - mse: 2532.2051
Epoch 91/200
3/3 [==============================] - 0s 4ms/step - loss: 2477.4099 - mse: 2477.4099
Epoch 92/200
3/3 [==============================] - 0s 4ms/step - loss: 2417.7275 - mse: 2417.7275
Epoch 93/200
3/3 [=====

3/3 [==============================] - 0s 5ms/step - loss: 136.0194 - mse: 136.0194
Epoch 167/200
3/3 [==============================] - 0s 5ms/step - loss: 124.7275 - mse: 124.7275
Epoch 168/200
3/3 [==============================] - 0s 4ms/step - loss: 121.4928 - mse: 121.4928
Epoch 169/200
3/3 [==============================] - 0s 5ms/step - loss: 105.4069 - mse: 105.4069
Epoch 170/200
3/3 [==============================] - 0s 5ms/step - loss: 100.5525 - mse: 100.5525
Epoch 171/200
3/3 [==============================] - 0s 4ms/step - loss: 77.2794 - mse: 77.2794
Epoch 172/200
3/3 [==============================] - 0s 5ms/step - loss: 73.0566 - mse: 73.0566
Epoch 173/200
3/3 [==============================] - 0s 5ms/step - loss: 74.8578 - mse: 74.8578
Epoch 174/200
3/3 [==============================] - 0s 4ms/step - loss: 65.2279 - mse: 65.2279
Epoch 175/200
3/3 [==============================] - 0s 4ms/step - loss: 55.7205 - mse: 55.7205
Epoch 176/200
3/3 [=========================

# 예측

In [27]:
# 문
a = model.predict([X_train[0].tolist()])

In [28]:
a.shape

(1, 1)

In [29]:
[[a[0].tolist()]]

[[[54.3925895690918]]]

In [30]:
b = X_train[0] + a[0].tolist()

In [31]:
b.shape

(71, 1)

In [32]:
np.concatenate([X_train[0],a])[1:].shape

(71, 1)

In [33]:
X_train[0].shape

(71, 1)

In [34]:
a.shape

(1, 1)

In [35]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [36]:
# input_height = 넘파이 배열 형식(2차원)
# n = 예측하고싶은 개월
# input_height = np.array([[50]])
def height_predict(model, input_height, n=72):
    max_len = 72
    for _ in range(len(input_height),n):# n번 반복
        encoded = pad_sequences(input_height, maxlen=max_len-1, padding='pre',dtype='float32').reshape(71,-1)
        result = model.predict([encoded.tolist()],verbose=0)
        input_height = np.hstack([input_height,result])
    return input_height

In [53]:
result = height_predict(model, np.array([[53,0]]))
result

array([[ 53.        ,   0.        ,  29.79663658,  54.15119171,
         60.87039566,  65.26405334,  68.6543808 ,  71.67779541,
         74.35643005,  76.81322479,  79.09413147,  81.20735168,
         83.15184021,  84.93746185,  86.59233093,  88.15690613,
         89.67608643,  91.19379425,  92.75109863,  94.38484192,
         96.1240387 ,  97.98035431,  99.92956543, 101.88619232,
        103.69428253, 105.1769104 , 106.23696899, 106.89176178,
        107.26644897, 107.46836853, 107.57310486, 107.62667847,
        107.65382385, 107.66751862, 107.67440796, 107.6778717 ,
        107.67961121, 107.68048096, 107.68091583, 107.68113708,
        107.6812439 , 107.6812973 , 107.68133545, 107.68134308,
        107.68134308, 107.68135071, 107.68135071, 107.68135071,
        107.68135071, 107.68135071, 107.68135071, 107.68135071,
        107.68135071, 107.68135071, 107.68135071, 107.68135071,
        107.68135071, 107.68135071, 107.68135071, 107.68135071,
        107.68135071, 107.68135071, 107.

In [38]:
# 사용할 모델, 토크나이저, 현재 단어, 생성할 단어 수
def sentence_generation(model, t, current_word, n): 
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기 위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        # 현재 단어에 대한 정수 인코딩
        encoded = t.texts_to_sequences([current_word])[0] 
        print(encoded)
        # 데이터를 같은 길이로 맞춤 (pre : 앞 부분에 0을 추가, post : 뒷 부분에 0을 추가)
        encoded = pad_sequences([encoded], maxlen=max_len-1, padding='pre') 
        # 입력한 X(현재 단어)에 대해서 y를 예측하고 y(예측한 단어)를 result에 저장.
        result = model.predict_classes(encoded, verbose=0)        
        
        for word, index in t.word_index.items(): 
            # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
            # 해당 단어가 예측 단어이므로 break
            if index == result: 
                break 
        # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경        
        current_word = current_word + ' '  + word 
        # 예측 단어를 문장에 저장
        sentence = sentence + ' ' + word 

    # 문장 생성
    sentence = init_word + sentence
    
    return sentence

In [39]:
# model_lstm = Sequential()

In [40]:
# model_lstm.add(Embedding(1000,32))
# model_lstm.add(LSTM(8))
# model_lstm.add(Dense(1, activation='sigmoid'))

In [41]:
# model_lstm.summary()

In [42]:
# model_lstm.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [43]:
# model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [44]:
# history = model_lstm.fit(X, y_en, epochs=100, batch_size=32, 
#                          validation_data=(X, y_en))