# 임포트 하기  

In [2]:
import pandas as pd
import numpy as np

# 데이터 불러오기 

In [3]:
!pip install openpyxl

In [5]:
girl=pd.read_excel('./data/여자 0-35개월 신장 백분위수.xlsx', engine='openpyxl')

In [6]:
boy=pd.read_excel('./data/남자 0-35개월 신장 백분위수.xlsx', engine='openpyxl')

# 데이터확인 

In [11]:
girl

만나이\n(개월)  신장(cm) 백분위수
0           0         49.1
1           1         53.7
2           2         57.1
3           3         59.8
4           4         62.1
..        ...          ...
67         67        112.1
68         68        112.6
69         69        113.2
70         70        113.7
71         71        114.2

[72 rows x 2 columns]

In [5]:
boy

만나이\n(개월)  신장(cm) 백분위수
0           0         49.9
1           1         54.7
2           2         58.4
3           3         61.4
4           4         63.9
..        ...          ...
67         67        113.3
68         68        113.8
69         69        114.4
70         70        114.9
71         71        115.4

[72 rows x 2 columns]

# 2개 이상의 모든 단의 조합을 생성

In [7]:
sequences = []
for i in range(1, len(boy)):
    sequence =boy.iloc[:i+1,1].values.tolist()
    sequences.append(sequence)

print('학습에 사용할 샘플의 개수: %d' % len(sequences))

학습에 사용할 샘플의 개수: 71


In [13]:
sequences

[[49.9, 54.7],
 [49.9, 54.7, 58.4],
 [49.9, 54.7, 58.4, 61.4],
 [49.9, 54.7, 58.4, 61.4, 63.9],
 [49.9, 54.7, 58.4, 61.4, 63.9, 65.9],
 [49.9, 54.7, 58.4, 61.4, 63.9, 65.9, 67.6],
 [49.9, 54.7, 58.4, 61.4, 63.9, 65.9, 67.6, 69.2],
 [49.9, 54.7, 58.4, 61.4, 63.9, 65.9, 67.6, 69.2, 70.6],
 [49.9, 54.7, 58.4, 61.4, 63.9, 65.9, 67.6, 69.2, 70.6, 72.0],
 [49.9, 54.7, 58.4, 61.4, 63.9, 65.9, 67.6, 69.2, 70.6, 72.0, 73.3],
 [49.9, 54.7, 58.4, 61.4, 63.9, 65.9, 67.6, 69.2, 70.6, 72.0, 73.3, 74.5],
 [49.9,
  54.7,
  58.4,
  61.4,
  63.9,
  65.9,
  67.6,
  69.2,
  70.6,
  72.0,
  73.3,
  74.5,
  75.7],
 [49.9,
  54.7,
  58.4,
  61.4,
  63.9,
  65.9,
  67.6,
  69.2,
  70.6,
  72.0,
  73.3,
  74.5,
  75.7,
  76.9],
 [49.9,
  54.7,
  58.4,
  61.4,
  63.9,
  65.9,
  67.6,
  69.2,
  70.6,
  72.0,
  73.3,
  74.5,
  75.7,
  76.9,
  78.0],
 [49.9,
  54.7,
  58.4,
  61.4,
  63.9,
  65.9,
  67.6,
  69.2,
  70.6,
  72.0,
  73.3,
  74.5,
  75.7,
  76.9,
  78.0,
  79.1],
 [49.9,
  54.7,
  58.4,
  61.4,
  63.

# 모든 샘플에서 길이가 가장 긴 샘플의 길이 출력 

In [14]:
print(max(len(l) for l in sequences))

72


# 입력할 내용을 일정한 길이로 변경 

In [8]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = 72

sequences = pad_sequences(sequences, maxlen=max_len, padding='pre',dtype='float32')

In [16]:
print(sequences)

[[  0.    0.    0.  ...   0.   49.9  54.7]
 [  0.    0.    0.  ...  49.9  54.7  58.4]
 [  0.    0.    0.  ...  54.7  58.4  61.4]
 ...
 [  0.    0.   49.9 ... 113.3 113.8 114.4]
 [  0.   49.9  54.7 ... 113.8 114.4 114.9]
 [ 49.9  54.7  58.4 ... 114.4 114.9 115.4]]


# 특성과 라벨을 분리 

In [9]:
import numpy as np

sequences = np.array(sequences)

X=sequences[:, : -1]
y=sequences[:, -1]

In [10]:
X_train = np.array(X)
y_train = np.array(y)

In [11]:
X_train

array([[  0. ,   0. ,   0. , ...,   0. ,   0. ,  49.9],
       [  0. ,   0. ,   0. , ...,   0. ,  49.9,  54.7],
       [  0. ,   0. ,   0. , ...,  49.9,  54.7,  58.4],
       ...,
       [  0. ,   0. ,  49.9, ..., 112.8, 113.3, 113.8],
       [  0. ,  49.9,  54.7, ..., 113.3, 113.8, 114.4],
       [ 49.9,  54.7,  58.4, ..., 113.8, 114.4, 114.9]], dtype=float32)

In [12]:
X_train = X_train.reshape(71,71,-1)

In [13]:
y_train = y_train.reshape(71,-1)

In [14]:
X_train

array([[[  0. ],
        [  0. ],
        [  0. ],
        ...,
        [  0. ],
        [  0. ],
        [ 49.9]],

       [[  0. ],
        [  0. ],
        [  0. ],
        ...,
        [  0. ],
        [ 49.9],
        [ 54.7]],

       [[  0. ],
        [  0. ],
        [  0. ],
        ...,
        [ 49.9],
        [ 54.7],
        [ 58.4]],

       ...,

       [[  0. ],
        [  0. ],
        [ 49.9],
        ...,
        [112.8],
        [113.3],
        [113.8]],

       [[  0. ],
        [ 49.9],
        [ 54.7],
        ...,
        [113.3],
        [113.8],
        [114.4]],

       [[ 49.9],
        [ 54.7],
        [ 58.4],
        ...,
        [113.8],
        [114.4],
        [114.9]]], dtype=float32)

In [15]:
y_train.shape

(71, 1)

# 원 핫 인코딩  

In [16]:
#from tensorflow.keras.utils import to_categorical

#y_en = to_categorical(y, dtype='float32')

In [17]:
#y_en

# RNN예측

In [18]:
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN, LSTM
from tensorflow.keras.models import Sequential

In [19]:
X.shape

(71, 71)

In [20]:
model = Sequential()
model.add(SimpleRNN(64,input_shape = (71,1)))
#model.add(SimpleRNN(32))
#입력 차원 지정(셀 개수 32개), 타임스텝 길이 100, 원핫인코딩 크기 100
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='relu'))
#이진분류 이므로 1개 유닛으 가짓 Dense층 추가

#model.summary() # 전체 구조 출력

In [21]:
model.compile(loss='mse',
    metrics=['mse'],)

In [23]:
history = model.fit(X_train, y_train , epochs=200)

Epoch 1/200
3/3 [==============================] - 0s 5ms/step - loss: 49.0728 - mse: 49.0728
Epoch 2/200
3/3 [==============================] - 0s 5ms/step - loss: 65.5156 - mse: 65.5156
Epoch 3/200
3/3 [==============================] - 0s 4ms/step - loss: 39.3238 - mse: 39.3238
Epoch 4/200
3/3 [==============================] - 0s 4ms/step - loss: 42.6826 - mse: 42.6826
Epoch 5/200
3/3 [==============================] - 0s 4ms/step - loss: 80.2876 - mse: 80.2876
Epoch 6/200
3/3 [==============================] - 0s 5ms/step - loss: 46.6217 - mse: 46.6217
Epoch 7/200
3/3 [==============================] - 0s 5ms/step - loss: 59.9710 - mse: 59.9710
Epoch 8/200
3/3 [==============================] - 0s 4ms/step - loss: 26.9398 - mse: 26.9398
Epoch 9/200
3/3 [==============================] - 0s 5ms/step - loss: 31.3532 - mse: 31.3532
Epoch 10/200
3/3 [==============================] - 0s 4ms/step - loss: 30.6784 - mse: 30.6784
Epoch 11/200
3/3 [==============================] - 0s 5ms/

3/3 [==============================] - 0s 5ms/step - loss: 2.8010 - mse: 2.8010
Epoch 89/200
3/3 [==============================] - 0s 4ms/step - loss: 8.0784 - mse: 8.0784
Epoch 90/200
3/3 [==============================] - 0s 4ms/step - loss: 4.2096 - mse: 4.2096
Epoch 91/200
3/3 [==============================] - 0s 5ms/step - loss: 1.4657 - mse: 1.4657
Epoch 92/200
3/3 [==============================] - 0s 4ms/step - loss: 1.0353 - mse: 1.0353
Epoch 93/200
3/3 [==============================] - 0s 4ms/step - loss: 3.1773 - mse: 3.1773
Epoch 94/200
3/3 [==============================] - 0s 5ms/step - loss: 10.4466 - mse: 10.4466
Epoch 95/200
3/3 [==============================] - 0s 4ms/step - loss: 4.0374 - mse: 4.0374
Epoch 96/200
3/3 [==============================] - 0s 4ms/step - loss: 5.4028 - mse: 5.4028
Epoch 97/200
3/3 [==============================] - 0s 4ms/step - loss: 1.7702 - mse: 1.7702
Epoch 98/200
3/3 [==============================] - 0s 5ms/step - loss: 0.8804 - 

3/3 [==============================] - 0s 5ms/step - loss: 13.2805 - mse: 13.2805
Epoch 176/200
3/3 [==============================] - 0s 5ms/step - loss: 14.1805 - mse: 14.1805
Epoch 177/200
3/3 [==============================] - 0s 5ms/step - loss: 0.9570 - mse: 0.9570
Epoch 178/200
3/3 [==============================] - 0s 4ms/step - loss: 0.4690 - mse: 0.4690
Epoch 179/200
3/3 [==============================] - 0s 4ms/step - loss: 1.6795 - mse: 1.6795
Epoch 180/200
3/3 [==============================] - 0s 4ms/step - loss: 7.9500 - mse: 7.9500
Epoch 181/200
3/3 [==============================] - 0s 4ms/step - loss: 3.0032 - mse: 3.0032
Epoch 182/200
3/3 [==============================] - 0s 5ms/step - loss: 3.2610 - mse: 3.2610
Epoch 183/200
3/3 [==============================] - 0s 5ms/step - loss: 2.3387 - mse: 2.3387
Epoch 184/200
3/3 [==============================] - 0s 4ms/step - loss: 2.3332 - mse: 2.3332
Epoch 185/200
3/3 [==============================] - 0s 4ms/step - los

# 예측

In [32]:
# 문
a = model.predict([X_train[0].tolist()])

In [80]:
a.shape

(1, 1)

In [81]:
[[a[0].tolist()]]

[[[52.75779342651367]]]

In [82]:
b = X_train[0] + a[0].tolist()

In [84]:
b.shape

(71, 1)

In [68]:
np.concatenate([X_train[0],a])[1:].shape

(71, 1)

In [65]:
X_train[0].shape

(71, 1)

In [66]:
a.shape

(1, 1)

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [24]:
# input_height = 넘파이 배열 형식(2차원)
# n = 예측하고싶은 개월
# input_height = np.array([[50]])
def height_predict(model, input_height, n=72):
    max_len = 72
    for _ in range(len(input_height),n):# n번 반복
        encoded = pad_sequences(input_height, maxlen=max_len-1, padding='pre',dtype='float32').reshape(71,-1)
        result = model.predict([encoded.tolist()],verbose=0)
        input_height = np.hstack([input_height,result])
    return input_height

In [31]:
result = height_predict(model, np.array([[50])
result

array([[ 49.9       ,  54.6307106 ,  59.82055664,  62.69232941,
         64.37195587,  66.06694031,  68.56568146,  71.27906036,
         73.75672913,  75.71913147,  78.51972198,  81.27294922,
         84.08570862,  87.25205231,  90.70883179,  94.45069122,
         98.19805145, 101.71838379, 104.71678925, 107.11614227,
        108.9983902 , 110.41756439, 111.439888  , 112.12726593,
        112.56876373, 112.83713531, 112.99414825, 113.08495331,
        113.13674164, 113.16606903, 113.18261719, 113.19192505,
        113.19716644, 113.20011139, 113.20175934, 113.20269012,
        113.20322418, 113.2035141 , 113.20368195, 113.2037735 ,
        113.20381927, 113.20383453, 113.20385742, 113.20386505,
        113.20387268, 113.20387268, 113.20387268, 113.20387268,
        113.20387268, 113.20387268, 113.20387268, 113.20387268,
        113.20387268, 113.20387268, 113.20387268, 113.20387268,
        113.20387268, 113.20387268, 113.20387268, 113.20387268,
        113.20387268, 113.20387268, 113.

In [30]:
len(result[0])

72

In [ ]:
# 사용할 모델, 토크나이저, 현재 단어, 생성할 단어 수
def sentence_generation(model, t, current_word, n): 
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기 위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        # 현재 단어에 대한 정수 인코딩
        encoded = t.texts_to_sequences([current_word])[0] 
        print(encoded)
        # 데이터를 같은 길이로 맞춤 (pre : 앞 부분에 0을 추가, post : 뒷 부분에 0을 추가)
        encoded = pad_sequences([encoded], maxlen=max_len-1, padding='pre') 
        # 입력한 X(현재 단어)에 대해서 y를 예측하고 y(예측한 단어)를 result에 저장.
        result = model.predict_classes(encoded, verbose=0)        
        
        for word, index in t.word_index.items(): 
            # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
            # 해당 단어가 예측 단어이므로 break
            if index == result: 
                break 
        # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경        
        current_word = current_word + ' '  + word 
        # 예측 단어를 문장에 저장
        sentence = sentence + ' ' + word 

    # 문장 생성
    sentence = init_word + sentence
    
    return sentence

In [ ]:
# model_lstm = Sequential()

In [ ]:
# model_lstm.add(Embedding(1000,32))
# model_lstm.add(LSTM(8))
# model_lstm.add(Dense(1, activation='sigmoid'))

In [ ]:
# model_lstm.summary()

In [ ]:
# model_lstm.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# history = model_lstm.fit(X, y_en, epochs=100, batch_size=32, 
#                          validation_data=(X, y_en))