In [5]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

# 임의의 데이터 입력 

In [7]:
# 단어 벡터의 차원은 5이고, 문장의 길이가 4인 경우를 가정한 입력 
# 4번의 시점(timesteps)이 존재하고, 각 시점마다 5차원의 단어 벡터가 입력으로 사용

train_X = [[0.1, 4.2, 1.5, 1.1, 2.8],[1.0, 3.1, 2.5, 0.7, 1.1],
          [0.3, 2.1, 1.5, 2.1, 0.1],[2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_X))

(4, 5)


In [8]:
#(batch_size, timesteps, imput_dim)에 해당되는 (1,4,5)의 크기를 가지는 3D텐서가 생성
#batch_size는 한 번에 RNN이 학습하는 데이터의 양을 의미하지만, 여기서는 샘플이 1개 밖에 없으므로  batch_size는 1입니다. 
train_X = [[[0.1,4.2,1.5,1.1,2.8],[1.0, 3.1, 2.5, 0.7, 1.1],[0.3, 2.1, 1.5, 2.1, 0.1],
          [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

(1, 4, 5)


In [9]:
rnn = SimpleRNN(3)
#rnn = SimpleRNN(3, return_sequences=False, return_state=Flase)와 동일,
hidden_state = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))

hidden state : [[-0.02272995  0.983162   -0.98211443]], shape: (1, 3)


In [11]:
#(1,4,3) 크기의 텐서가 출력된다. 앞서 입력 데이터는 (1,4,5)의 크기를 가지는 3D 텐서였고,
# 그 중 4가 시점(timesteps)에 해당하는 값이므로 모든 시점에 대해서 은닉 상태의 값으 
# 출력하여 (1,4,3) 크기의 텐서를 출력하는 것 

# return_state가 True일 경우에는 return_sequences 의 True/False 여부와 상관없이 마지막
# 시점의 은닉상태를 출력한다.
# 가령 return_sequences 가 True이면서, return_state를 True로 할 경우 SimpleRNN은 두개의 출력을 리턴 

rnn = SimpleRNN(3, return_sequences=True)
#rnn = SimpleRNN(3, return_sequences=False, return_state=Flase)와 동일,
hidden_state = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))

hidden state : [[[ 0.9997726  -0.98913187 -0.9765868 ]
  [ 0.9858561  -0.9996745  -0.99795026]
  [ 0.9398904  -0.9749888  -0.812145  ]
  [ 0.9974704  -0.99900705 -0.9795453 ]]], shape: (1, 4, 3)


In [12]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_X)

#첫번째 출력은 return_sequnces=True로 인한 출력으로 모든 시점의 은닉상태입니다.
# 두번째 출력은 return_state=True로 인한 출력으로 마지막 시점의 은닉 상태 입니다. 

print('hidden states : {}, shape:{}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

hidden states : [[[-0.801984   -0.60153973 -0.55489635]
  [-0.255125    0.9285481  -0.10664317]
  [ 0.97551525  0.9496744  -0.52859545]
  [ 0.9507652  -0.9189157  -0.12111226]]], shape:(1, 4, 3)
last hidden state : [[ 0.9507652  -0.9189157  -0.12111226]], shape: (1, 3)


In [13]:
rnn = SimpleRNN(3, return_sequences=False, return_state=True)
hidden_state, last_state = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

hidden state : [[0.9103206  0.9984854  0.67183256]], shape: (1, 3)
last hidden state : [[0.9103206  0.9984854  0.67183256]], shape: (1, 3)


In [15]:
#이번에는 SimpleRNN 때와는 달리, 세 개의 결과를 반환합니다.
#return_sequences가 False이므로 우선 첫번째 결과는 마지막 시점의 은닉 상태입니다. 그런데 LSTM이 SimpleRNN과 다른 점은 return_state를 True로 둔 경우에는 마지막 시점의 은닉 상태뿐만 아니라 셀 상태까지 반환한다는 점입니다. 
#이번에는 return_sequences를 True로 바꿔보겠습니다.
lstm = LSTM(3, return_sequences=False, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

hidden state : [[ 0.36159617 -0.35566586  0.24180943]], shape: (1, 3)
last hidden state : [[ 0.36159617 -0.35566586  0.24180943]], shape: (1, 3)
last cell state : [[ 0.73386854 -0.767523    0.3616745 ]], shape: (1, 3)


In [16]:
#return_state가 True이므로 두번째 출력값이 마지막 은닉 상태, 세번째 출력값이 마지막 셀 상태인 것은 변함없지만
#return_sequences가 True이므로 첫번째 출력값은 모든 시점의 은닉 상태가 출력됩니다.
lstm = LSTM(3, return_sequences=True, return_state=True)
hidden_states, last_hidden_state, last_cell_state = lstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_hidden_state, last_hidden_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

hidden states : [[[-0.22586721 -0.7252694   0.02232654]
  [-0.22706778 -0.86743957  0.15447804]
  [-0.30271626 -0.85385174  0.11967059]
  [-0.22883801 -0.32943812  0.29019538]]], shape: (1, 4, 3)
last hidden state : [[-0.22883801 -0.32943812  0.29019538]], shape: (1, 3)
last cell state : [[-0.9799297  -0.37638602  0.87705386]], shape: (1, 3)


In [17]:
k_init = tf.keras.initializers.Constant(value=0.1)
b_init = tf.keras.initializers.Constant(value=0)
r_init = tf.keras.initializers.Constant(value=0.1)

In [29]:
import pandas as pd
import xlrd

In [33]:
pd.read_excel('.C:\Users\smhrd\Desktop/data/연령별_신장.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: './data/연령별_신장.xlsx'