# 임포트하기

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
tf.compat.v1.disable_eager_execution()
tf.compat.v1.random.set_random_seed(777)

# 데이터셋

In [2]:
train=pd.read_csv('./data/영유아키.csv' , encoding="utf-8")
test=pd.read_csv('./data/테스트.csv' , encoding='utf-8')

In [3]:
train = pd.concat([train, pd.get_dummies(train['성별'])], axis = 1)
test = pd.concat([test, pd.get_dummies(test['성별'])], axis = 1)
del train['성별']
del test['성별']

In [4]:
# 부모키 삽입하기
# pd.concat 사용해서 train, test에 부모키 추가

In [5]:
train

1~2개월  2~3개월  3~4개월  4~5개월   5~6개월  6~7개월  7~8개월  8~9개월  9~10개월  \
0     57.49  59.96  62.92   64.70  66.89  67.94  69.89  71.38   72.35   
1     58.22  59.56  62.55   62.68  65.53  66.98  67.97  68.66   70.11   
2     59.34  60.99  61.52   63.78  66.39  67.46  68.90  70.04   71.82   
3     58.57  59.85  60.05   60.56  60.56  61.09  62.47  64.84   64.99   
4     58.79  61.16  62.61   64.38  65.76  67.98  70.19  72.69   74.70   
...     ...    ...    ...     ...    ...    ...    ...    ...     ...   
4995  55.09  56.31  57.15   58.21  60.85  61.31  64.04  65.08   67.95   
4996  55.12  56.49  56.71   59.20  59.49  61.23  64.20  65.89   67.32   
4997  58.32  59.31  60.08   60.52  61.33  63.73  63.73  64.94   66.68   
4998  59.44  62.03  64.02   65.26  65.91  66.63  68.34  70.98   73.84   
4999  54.34  55.80  57.71   58.93  59.98  62.80  65.03  66.16   68.96   

      10~11개월  ...  12~15개월  15~18개월  18~21개월\t  21~24개월\t     2세     3세  \
0       74.04  ...    79.85    83.47      87.07      88.17  90.29  93.53   
1       72.45  ...    75.46    77.42      79.27      83.78  84.81  88.74   
2       72.55  ...    78.30    81.85      83.60      86.97  91.24  99.58   
3       65.94  ...    72.24    76.49      79.51      84.21  85.57  94.15   
4       75.48  ...    79.85    81.13      83.88      86.52  90.42  97.55   
...       ...  ...      ...      ...        ...        ...    ...    ...   
4995    70.39  ...    74.24    76.29      80.64      85.32  87.87  96.79   
4996    69.67  ...    74.77    76.37      79.42      83.24  84.51  93.04   
4997    69.60  ...    76.00    79.40      83.33      85.83  87.36  91.91   
4998    75.19  ...    77.37    79.22      81.45      85.11  88.24  95.16   
4999    70.43  ...    75.22    79.25      82.06      85.58  90.52  96.52   

          4세      5세  남  여  
0      99.69  108.59  1  0  
1      97.63  102.45  1  0  
2     103.53  107.92  1  0  
3     101.46  105.12  1  0  
4     101.60  109.79  1  0  
...      ...     ... .. ..  
4995  106.24  112.64  0  1  
4996   97.96  105.02  0  1  
4997  100.95  109.03  0  1  
4998  101.89  107.08  0  1  
4999  106.19  109.87  0  1  

[5000 rows x 21 columns]

In [6]:
test

1~2개월  2~3개월  3~4개월  4~5개월   5~6개월  6~7개월  7~8개월  8~9개월  9~10개월  \
0     54.09  54.32  56.94   59.52  61.78  61.89  64.76  65.85   67.90   
1     56.17  56.43  57.68   58.75  61.23  62.72  64.88  65.16   65.25   
2     58.43  58.44  60.13   60.57  60.68  60.86  63.30  66.05   68.23   
3     54.06  56.04  58.47   60.45  62.87  63.00  63.00  63.46   65.51   
4     54.13  54.69  55.46   57.29  59.06  59.23  62.18  63.56   65.44   
...     ...    ...    ...     ...    ...    ...    ...    ...     ...   
4995  57.50  59.99  60.96   62.53  64.11  64.32  64.65  67.42   67.61   
4996  56.45  58.84  59.61   60.52  61.72  62.40  64.32  64.68   66.47   
4997  55.49  57.25  58.92   60.60  63.31  64.82  66.54  66.73   69.24   
4998  57.97  59.36  61.30   63.36  63.73  64.60  65.99  67.29   69.29   
4999  55.36  57.49  59.52   60.28  62.24  62.91  64.97  65.24   66.44   

      10~11개월  ...  12~15개월  15~18개월  18~21개월\t  21~24개월\t     2세      3세  \
0       69.44  ...    72.78    76.91      81.61      86.57  89.33   95.29   
1       65.46  ...    68.69    72.18      75.53      76.59  77.85   81.91   
2       70.11  ...    74.68    79.20      82.02      86.52  90.42  100.40   
3       66.40  ...    70.75    75.21      77.60      81.76  84.36   89.47   
4       66.91  ...    70.56    72.51      74.14      78.71  81.10   89.40   
...       ...  ...      ...      ...        ...        ...    ...     ...   
4995    68.16  ...    74.90    78.22      82.18      87.08  91.12  100.20   
4996    67.41  ...    70.36    74.23      76.83      78.15  80.22   88.66   
4997    69.93  ...    76.33    78.69      82.14      86.68  88.06   96.60   
4998    71.46  ...    74.74    78.72      80.26      81.75  84.51   93.84   
4999    68.14  ...    73.22    76.01      77.17      82.01  84.12   88.30   

          4세      5세  남  여  
0     102.07  107.69  1  0  
1      87.47   92.28  1  0  
2     105.82  114.49  1  0  
3      95.74  104.82  1  0  
4      93.98  103.80  1  0  
...      ...     ... .. ..  
4995  107.99  117.96  0  1  
4996   92.70   99.91  0  1  
4997  105.08  109.03  0  1  
4998  102.56  111.58  0  1  
4999   91.60   98.83  0  1  

[5000 rows x 21 columns]

In [7]:
# 부모키 추가시
X_train = np.array(train.drop('5세',axis = 1))
y_train = np.array(train.iloc[:,-5].copy())
X_test = np.array(test.drop('5세',axis = 1))
y_test = np.array(test.iloc[:,-5].copy())

In [8]:
X_train = np.array(train.drop('5세',axis = 1))
y_train = np.array(train.iloc[:,-3].copy())
X_test = np.array(test.drop('5세',axis = 1))
y_test = np.array(test.iloc[:,-3].copy())

In [9]:
X_train = X_train.reshape(5000,20,-1)
y_train = y_train.reshape(5000,-1)

In [10]:
X_test = X_test.reshape(5000,20,-1)
y_test = y_test.reshape(5000,-1)

In [11]:
# tensorflow --> 딥러닝 모델 기초설계
# tensorflow.keras --> tensorflow를 사용하기쉽게 해주는 라이브러리
import tensorflow.keras as tf
from tensorflow.keras.layers import Dense

## 부모키 추가했을 때 

In [12]:
# # 부모키 추가시
# sequential_model = tf.Sequential() # tf.Sequential() --> 기본틀 

# sequential_model.add(Dense(10,  activation='relu', input_shape = [22]))
    
# # hidden layer
# sequential_model.add(Dense(64, activation='relu')) #Dense 하나하나가 hidden layer

# sequential_model.add(Dense(64, activation='relu'))

# # output layer
# sequential_model.add(Dense(1, activation='relu')) # activation function 에대해 조사할것

## 아이키만 사용했을 때

In [13]:
from tensorflow.keras.layers import RNN, Embedding, LSTM, SimpleRNN

In [14]:
sequential_model = tf.Sequential() # tf.Sequential() --> 기본틀 

sequential_model.add(SimpleRNN(64,input_shape = (20,1)))
#sequential_model.add(Dense(10,  activation='relu', input_shape = [20]))
    
# hidden layer
#sequential_model.add(Dense(64, activation='relu')) #Dense 하나하나가 hidden layer

#sequential_model.add(Dense(64, activation='relu'))

# output layer
sequential_model.add(Dense(10, activation='relu'))
#sequential_model.add(Dense(5, activation='relu'))
sequential_model.add(Dense(1, activation='relu')) # activation function 에대해 조사할것

In [15]:
sequential_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 64)                4224      
                                                                 
 dense (Dense)               (None, 10)                650       
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 4,885
Trainable params: 4,885
Non-trainable params: 0
_________________________________________________________________


In [16]:
sequential_model.compile( optimizer='rmsprop',
                         loss = 'mean_squared_error'
                    )

In [17]:
sequential_model.fit(X_train,
                     y_train,
                     batch_size=None, # 몇 개로 나누어 동시에 진행할 것인가
                     epochs=10, # 훈련 몇번 진행할 것인지
                     validation_split=0.2); # train데이터에서 일정 비율만큼 쪽지시험으로 놔둔다.

Train on 4000 samples, validate on 1000 samples
Epoch 1/10
4000/4000 [==============================] - 0s 109us/sample - loss: 9144.3696 - val_loss: 7794.4656
Epoch 2/10
2272/4000 [================>.............] - ETA: 0s - loss: 7046.4315

C:\Users\smhrd\anaconda3\lib\site-packages\keras\engine\training_v1.py:2057: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates = self.state_updates


4000/4000 [==============================] - 0s 50us/sample - loss: 6511.8753 - val_loss: 5232.9022
Epoch 3/10
4000/4000 [==============================] - 0s 49us/sample - loss: 3969.1995 - val_loss: 2768.4329
Epoch 4/10
4000/4000 [==============================] - 0s 49us/sample - loss: 1746.1847 - val_loss: 874.1621
Epoch 5/10
4000/4000 [==============================] - 0s 49us/sample - loss: 357.5461 - val_loss: 51.4971
Epoch 6/10
4000/4000 [==============================] - 0s 49us/sample - loss: 31.5700 - val_loss: 30.0521
Epoch 7/10
4000/4000 [==============================] - 0s 49us/sample - loss: 29.7739 - val_loss: 30.0899
Epoch 8/10
4000/4000 [==============================] - 0s 49us/sample - loss: 29.7770 - val_loss: 30.1490
Epoch 9/10
4000/4000 [==============================] - 0s 49us/sample - loss: 29.8139 - val_loss: 30.2546
Epoch 10/10
4000/4000 [==============================] - 0s 49us/sample - loss: 29.8028 - val_loss: 30.0245


In [18]:
# 예측 
sequential_model.predict(X_test[0].reshape(1,20,-1))

C:\Users\smhrd\anaconda3\lib\site-packages\keras\engine\training_v1.py:2079: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


array([[106.517395]], dtype=float32)

In [19]:
X_test[0]

array([[ 54.09],
       [ 54.32],
       [ 56.94],
       [ 59.52],
       [ 61.78],
       [ 61.89],
       [ 64.76],
       [ 65.85],
       [ 67.9 ],
       [ 69.44],
       [ 71.09],
       [ 72.78],
       [ 76.91],
       [ 81.61],
       [ 86.57],
       [ 89.33],
       [ 95.29],
       [102.07],
       [  1.  ],
       [  0.  ]])

In [20]:
x = [[ 54.09],
       [ 54.32],
       [ 56.94],
       [ 59.52],
       [ 61.78],
       [ 61.89],
       [ 64.76],
       [ 65.85],
       [ 67.9 ],
       [ 69.44],
       [ 71.09],
       [ 72.78],
       [ 76.91],
       [ 81.61],
       [ 86.57],
       [ 89.33],
       [ 95.29],
       [102.07],
       [  1.  ],
       [  0.  ]]

In [21]:
x

[[54.09],
 [54.32],
 [56.94],
 [59.52],
 [61.78],
 [61.89],
 [64.76],
 [65.85],
 [67.9],
 [69.44],
 [71.09],
 [72.78],
 [76.91],
 [81.61],
 [86.57],
 [89.33],
 [95.29],
 [102.07],
 [1.0],
 [0.0]]

In [23]:
x=np.array(x)
x

array([[ 54.09],
       [ 54.32],
       [ 56.94],
       [ 59.52],
       [ 61.78],
       [ 61.89],
       [ 64.76],
       [ 65.85],
       [ 67.9 ],
       [ 69.44],
       [ 71.09],
       [ 72.78],
       [ 76.91],
       [ 81.61],
       [ 86.57],
       [ 89.33],
       [ 95.29],
       [102.07],
       [  1.  ],
       [  0.  ]])

In [22]:
sequential_model.predict(x.reshape(1,20,-1))

AttributeError: 'list' object has no attribute 'reshape'

In [ ]:
# import tensorflow as tf
# import pandas as pd
# import numpy as np
# tf.compat.v1.disable_eager_execution()
# tf.compat.v1.random.set_random_seed(777)

# test=pd.read_csv('./data/영유아키.csv' , encoding="utf-8")
# train=pd.read_csv('./data/테스트.csv' , encoding='euc-kr')

# train = pd.concat([train, pd.get_dummies(train['성별'])], axis = 1)
# test = pd.concat([test, pd.get_dummies(test['성별'])], axis = 1)
# del train['성별']
# del test['성별']

# X_train = np.array(train.drop('5세',axis = 1))
# y_train = np.array(train.iloc[:,-3].copy())
# X_test = np.array(test.drop('5세',axis = 1))
# y_test = np.array(test.iloc[:,-3].copy())

# # tensorflow --> 딥러닝 모델 기초설계
# # tensorflow.keras --> tensorflow를 사용하기쉽게 해주는 라이브러리
# import tensorflow.keras as tf
# from tensorflow.keras.layers import Dense

# sequential_model = tf.Sequential() # tf.Sequential() --> 기본틀 

# sequential_model.add(Dense(10,  activation='relu', input_shape = [20]))
    
# # hidden layer
# sequential_model.add(Dense(64, activation='relu')) #Dense 하나하나가 hidden layer

# sequential_model.add(Dense(64, activation='relu'))

# # output layer
# sequential_model.add(Dense(1, activation='relu')) # activation function 에대해 조사할것

# sequential_model.compile( optimizer='rmsprop',
#                          loss = 'mse'
#                     )

# sequential_model.fit(X_train,
#                      y_train,
#                      batch_size=None, # 몇 개로 나누어 동시에 진행할 것인가
#                      epochs=100, # 훈련 몇번 진행할 것인지
#                      validation_split=0.2); # train데이터에서 일정 비율만큼 쪽지시험으로 놔둔다.

# X_test[0].reshape(1,-1)

# sequential_model.predict(X_test[0].reshape(1,-1))

In [ ]:
#sequential_model.save('dodam.h5')

In [ ]:
sequential_model.predict(new_data)