# 임포트하기

In [1]:
pip install --upgrade tensorflow

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install ipykernel

Note: you may need to restart the kernel to use updated packages.


In [3]:
import tensorflow as tf
import pandas as pd
import numpy as np
tf.compat.v1.disable_eager_execution()
tf.compat.v1.random.set_random_seed(777)

# 데이터셋

In [4]:
train=pd.read_csv('./data/영유아키.csv' , encoding="utf-8")
test=pd.read_csv('./data/테스트.csv' , encoding='euc-kr')

In [5]:
train = pd.concat([train, pd.get_dummies(train['성별'])], axis = 1)
test = pd.concat([test, pd.get_dummies(test['성별'])], axis = 1)
del train['성별']
del test['성별']

In [6]:
# 부모키 삽입하기
# pd.concat 사용해서 train, test에 부모키 추가

In [7]:
test

1~2개월  2~3개월  3~4개월  4~5개월   5~6개월  6~7개월  7~8개월  8~9개월  9~10개월  \
0     50.96  60.52  63.12   65.68  67.07  69.55  70.86  72.61   73.55   
1     50.31  60.92  63.04   65.24  67.16  69.46  70.73  72.89   73.88   
2     50.37  60.84  63.27   65.39  67.68  69.54  70.02  72.78   73.88   
3     50.25  60.64  63.11   65.05  67.26  69.11  70.65  72.13   73.86   
4     50.53  60.70  63.24   65.90  67.55  69.21  70.05  72.75   73.32   
...     ...    ...    ...     ...    ...    ...    ...    ...     ...   
9995  56.54  59.97  62.43   64.18  66.99  68.74  70.09  70.60   73.58   
9996  56.17  59.01  62.59   64.28  66.43  68.46  70.24  70.50   73.31   
9997  56.70  59.55  62.83   64.96  66.43  68.21  70.08  70.76   73.99   
9998  56.47  59.62  62.89   64.95  66.89  68.77  71.00  70.44   73.48   
9999  56.48  59.31  62.16   64.29  66.91  68.10  70.60  70.57   73.49   

      10~11개월  ...  12~15개월  15~18개월  18~21개월\t  21~24개월\t     2세      3세  \
0       74.91  ...    78.71    81.54      83.71      86.20  93.88  103.07   
1       74.09  ...    78.27    81.27      83.25      86.78  93.60  103.78   
2       74.57  ...    78.01    81.35      83.10      86.66  93.67  103.47   
3       74.99  ...    78.87    81.25      83.54      86.88  93.46  103.11   
4       74.74  ...    78.23    81.16      83.55      86.60  93.32  103.85   
...       ...  ...      ...      ...        ...        ...    ...     ...   
9995    73.98  ...    76.99    79.82      82.83      84.87  91.06   99.77   
9996    73.91  ...    76.05    79.87      82.97      84.73  91.15   99.98   
9997    73.99  ...    76.75    79.28      82.90      84.04  91.32   99.87   
9998    73.57  ...    76.71    79.96      82.83      84.45  91.91   99.32   
9999    73.10  ...    76.85    79.78      82.84      84.83  91.43   99.64   

          4세      5세  남  여  
0     107.42  113.34  1  0  
1     107.44  113.30  1  0  
2     107.39  113.60  1  0  
3     107.52  113.97  1  0  
4     107.69  113.15  1  0  
...      ...     ... .. ..  
9995  106.86  112.30  0  1  
9996  106.66  112.90  0  1  
9997  106.11  112.02  0  1  
9998  106.82  112.38  0  1  
9999  106.29  112.85  0  1  

[10000 rows x 21 columns]

In [8]:
# 부모키 추가시
X_train = np.array(train.drop('5세',axis = 1))
y_train = np.array(train.iloc[:,-5].copy())
X_test = np.array(test.drop('5세',axis = 1))
y_test = np.array(test.iloc[:,-5].copy())

In [9]:
X_train = np.array(train.drop('5세',axis = 1))
y_train = np.array(train.iloc[:,-3].copy())
X_test = np.array(test.drop('5세',axis = 1))
y_test = np.array(test.iloc[:,-3].copy())

In [10]:
# tensorflow --> 딥러닝 모델 기초설계
# tensorflow.keras --> tensorflow를 사용하기쉽게 해주는 라이브러리
import tensorflow.keras as tf
from tensorflow.keras.layers import Dense

## 부모키 추가했을 때 

In [11]:
# 부모키 추가시
sequential_model = tf.Sequential() # tf.Sequential() --> 기본틀 

sequential_model.add(Dense(10,  activation='relu', input_shape = [22]))
    
# hidden layer
sequential_model.add(Dense(64, activation='relu')) #Dense 하나하나가 hidden layer

sequential_model.add(Dense(64, activation='relu'))

# output layer
sequential_model.add(Dense(1, activation='relu')) # activation function 에대해 조사할것

## 아이키만 사용했을 때

In [12]:

sequential_model = tf.Sequential() # tf.Sequential() --> 기본틀 

sequential_model.add(Dense(10,  activation='relu', input_shape = [20]))
    
# hidden layer
sequential_model.add(Dense(64, activation='relu')) #Dense 하나하나가 hidden layer

sequential_model.add(Dense(64, activation='relu'))

# output layer
sequential_model.add(Dense(1, activation='relu')) # activation function 에대해 조사할것

In [13]:
sequential_model.compile( optimizer='rmsprop',
                         loss = 'mse'
                    )

In [14]:
sequential_model.fit(X_train,
                     y_train,
                     batch_size=None, # 몇 개로 나누어 동시에 진행할 것인가
                     epochs=100, # 훈련 몇번 진행할 것인지
                     validation_split=0.2); # train데이터에서 일정 비율만큼 쪽지시험으로 놔둔다.

Train on 4000 samples, validate on 1000 samples
Epoch 1/100
4000/4000 [==============================] - 0s 51us/sample - loss: 264.0703 - val_loss: 23.1506
Epoch 2/100
4000/4000 [==============================] - 0s 14us/sample - loss: 17.6459 - val_loss: 10.5298
Epoch 3/100
4000/4000 [==============================] - 0s 14us/sample - loss: 14.4316 - val_loss: 16.7135
Epoch 4/100
4000/4000 [==============================] - 0s 14us/sample - loss: 12.9868 - val_loss: 11.2302


C:\Users\smhrd\anaconda3\lib\site-packages\keras\engine\training_v1.py:2057: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates = self.state_updates


Epoch 5/100
4000/4000 [==============================] - 0s 14us/sample - loss: 11.3782 - val_loss: 6.2471
Epoch 6/100
4000/4000 [==============================] - 0s 14us/sample - loss: 9.9128 - val_loss: 9.9372
Epoch 7/100
4000/4000 [==============================] - 0s 13us/sample - loss: 9.2814 - val_loss: 20.2787
Epoch 8/100
4000/4000 [==============================] - 0s 14us/sample - loss: 8.7163 - val_loss: 11.7906
Epoch 9/100
4000/4000 [==============================] - 0s 14us/sample - loss: 7.9548 - val_loss: 9.6468
Epoch 10/100
4000/4000 [==============================] - 0s 14us/sample - loss: 7.5683 - val_loss: 6.8974
Epoch 11/100
4000/4000 [==============================] - 0s 14us/sample - loss: 7.1864 - val_loss: 6.9934
Epoch 12/100
4000/4000 [==============================] - 0s 14us/sample - loss: 6.8160 - val_loss: 5.2590
Epoch 13/100
4000/4000 [==============================] - 0s 13us/sample - loss: 6.7393 - val_loss: 7.0073
Epoch 14/100
4000/4000 [===============

4000/4000 [==============================] - 0s 14us/sample - loss: 3.0934 - val_loss: 2.1489
Epoch 82/100
4000/4000 [==============================] - 0s 14us/sample - loss: 3.0116 - val_loss: 1.3907
Epoch 83/100
4000/4000 [==============================] - 0s 13us/sample - loss: 3.0554 - val_loss: 3.2098
Epoch 84/100
4000/4000 [==============================] - 0s 14us/sample - loss: 3.0378 - val_loss: 3.5528
Epoch 85/100
4000/4000 [==============================] - 0s 14us/sample - loss: 3.0578 - val_loss: 2.3615
Epoch 86/100
4000/4000 [==============================] - 0s 14us/sample - loss: 3.0395 - val_loss: 2.6030
Epoch 87/100
4000/4000 [==============================] - 0s 14us/sample - loss: 2.9909 - val_loss: 4.1033
Epoch 88/100
4000/4000 [==============================] - 0s 14us/sample - loss: 3.0104 - val_loss: 2.9025
Epoch 89/100
4000/4000 [==============================] - 0s 14us/sample - loss: 3.0047 - val_loss: 2.4391
Epoch 90/100
4000/4000 [==========================

In [15]:
X_test[0].reshape(1,-1)

array([[ 50.96,  60.52,  63.12,  65.68,  67.07,  69.55,  70.86,  72.61,
         73.55,  74.91,  76.49,  78.71,  81.54,  83.71,  86.2 ,  93.88,
        103.07, 107.42,   1.  ,   0.  ]])

In [16]:
# 예측 
sequential_model.predict(X_test[0].reshape(1, -1 ))

C:\Users\smhrd\anaconda3\lib\site-packages\keras\engine\training_v1.py:2079: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


array([[111.45145]], dtype=float32)

In [69]:
x=[[ 50.96,  51.52,  52.12,  53.68,  0,  55.55,  56.86,  57.61,
         58.55,  59.91,  60.49,  61.71,  62.54,  63.71,  67.2 ,  73.88,
        82.07, 92.42,   1.  ,   0.  ]]

In [71]:
x=np.array(x)

In [72]:
x

array([[50.96, 51.52, 52.12, 53.68,  0.  , 55.55, 56.86, 57.61, 58.55,
        59.91, 60.49, 61.71, 62.54, 63.71, 67.2 , 73.88, 82.07, 92.42,
         1.  ,  0.  ]])

In [73]:
sequential_model.predict(x.reshape(1, -1 ))

array([[75.668365]], dtype=float32)