# 임포트 하기  

In [1]:
import pandas as pd
import numpy as np

# 데이터 불러오기 

In [2]:
key =pd.read_excel('./data/키데이터.xlsx')

# 데이터확인 

In [3]:
key = key.T

In [4]:
key

0       1       2       3       4       5       6       7       8   \
0    50.06   47.48   50.99   47.83   48.40   52.23   50.92   48.88   50.65   
1    50.89   48.40   52.46   49.35   49.65   52.60   51.90   49.90   51.88   
2    51.15   49.64   52.79   50.23   49.88   52.92   52.83   50.91   53.08   
3    52.55   50.63   54.14   51.12   51.42   53.22   53.45   52.35   53.57   
4    52.69   50.81   54.78   51.86   52.73   54.80   54.82   53.14   53.92   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
67  114.13  107.27  108.41  109.26  106.82  116.75  108.10  104.25  108.86   
68  114.29  108.20  109.40  109.70  107.83  117.86  108.20  104.56  110.51   
69  115.44  108.54  110.83  110.73  109.47  119.45  109.01  104.94  111.05   
70  116.50  110.16  112.31  111.31  110.29  120.99  110.41  106.36  111.16   
71  117.07  111.02  112.45  111.74  111.09  121.84  111.93  107.62  111.34   

        9   ...      90      91      92      93      94      95      96  \
0    49.01  ...   48.89   51.30   51.93   52.16   49.23   51.11   51.50   
1    50.31  ...   49.17   52.97   52.28   53.26   50.40   51.24   51.61   
2    51.21  ...   50.23   54.64   52.39   54.56   51.60   51.64   52.96   
3    51.35  ...   51.70   54.82   53.73   55.61   52.50   52.49   54.11   
4    51.53  ...   52.98   56.07   54.17   56.10   53.79   53.18   54.64   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
67  110.22  ...  110.62  110.08  107.16  111.07  108.83  111.42  112.32   
68  110.34  ...  112.34  110.98  108.43  111.50  110.21  112.51  113.93   
69  110.89  ...  112.65  112.50  108.68  111.91  111.48  112.84  115.45   
70  111.89  ...  113.36  112.82  109.15  112.31  112.86  113.71  115.60   
71  113.13  ...  114.93  113.56  110.85  113.22  113.66  115.23  115.84   

        97      98      99  
0    50.80   47.23   50.95  
1    51.69   48.32   51.40  
2    53.23   49.33   53.11  
3    54.93   50.29   53.59  
4    55.81   52.01   54.55  
..     ...     ...     ...  
67  116.37  111.40  112.23  
68  117.31  112.93  113.17  
69  118.22  113.62  114.21  
70  118.52  114.94  115.90  
71  119.38  116.59  116.88  

[72 rows x 100 columns]

# 2개 이상의 모든 단의 조합을 생성

In [5]:
temp = pd.DataFrame(key[0])
temp.columns=['g']

In [6]:
temp

g
0    50.06
1    50.89
2    51.15
3    52.55
4    52.69
..     ...
67  114.13
68  114.29
69  115.44
70  116.50
71  117.07

[72 rows x 1 columns]

In [7]:
len(key.columns)

100

In [8]:
key[2]

0      50.99
1      52.46
2      52.79
3      54.14
4      54.78
       ...  
67    108.41
68    109.40
69    110.83
70    112.31
71    112.45
Name: 2, Length: 72, dtype: float64

In [9]:
key_seq = []
for i in range(len(key.columns)):
    temp = pd.DataFrame(key[i])
    temp.columns=['g']
    temp[1] = range(72)
    temp = temp[[1,'g']]
    for j in range (1,len(temp)):
        seq = temp.iloc[:j+1,1].values.tolist()
        key_seq.append(seq)
    del temp

print('학습에 사용할 샘플의 개수: %d' % len(key_seq))

학습에 사용할 샘플의 개수: 7100


In [10]:
key_seq

[[50.06, 50.89],
 [50.06, 50.89, 51.15],
 [50.06, 50.89, 51.15, 52.55],
 [50.06, 50.89, 51.15, 52.55, 52.69],
 [50.06, 50.89, 51.15, 52.55, 52.69, 53.76],
 [50.06, 50.89, 51.15, 52.55, 52.69, 53.76, 54.83],
 [50.06, 50.89, 51.15, 52.55, 52.69, 53.76, 54.83, 55.61],
 [50.06, 50.89, 51.15, 52.55, 52.69, 53.76, 54.83, 55.61, 57.32],
 [50.06, 50.89, 51.15, 52.55, 52.69, 53.76, 54.83, 55.61, 57.32, 58.6],
 [50.06, 50.89, 51.15, 52.55, 52.69, 53.76, 54.83, 55.61, 57.32, 58.6, 59.74],
 [50.06,
  50.89,
  51.15,
  52.55,
  52.69,
  53.76,
  54.83,
  55.61,
  57.32,
  58.6,
  59.74,
  61.09],
 [50.06,
  50.89,
  51.15,
  52.55,
  52.69,
  53.76,
  54.83,
  55.61,
  57.32,
  58.6,
  59.74,
  61.09,
  61.980000000000004],
 [50.06,
  50.89,
  51.15,
  52.55,
  52.69,
  53.76,
  54.83,
  55.61,
  57.32,
  58.6,
  59.74,
  61.09,
  61.980000000000004,
  63.040000000000006],
 [50.06,
  50.89,
  51.15,
  52.55,
  52.69,
  53.76,
  54.83,
  55.61,
  57.32,
  58.6,
  59.74,
  61.09,
  61.980000000000004

# 모든 샘플에서 길이가 가장 긴 샘플의 길이 출력 

In [11]:
print(max(len(l) for l in key_seq))

72


# 입력할 내용을 일정한 길이로 변경 

In [12]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = 72

key_seq = pad_sequences(key_seq, maxlen=max_len, padding='pre',dtype='float32')

In [13]:
print(key_seq)

[[  0.     0.     0.   ...   0.    50.06  50.89]
 [  0.     0.     0.   ...  50.06  50.89  51.15]
 [  0.     0.     0.   ...  50.89  51.15  52.55]
 ...
 [  0.     0.    50.95 ... 112.23 113.17 114.21]
 [  0.    50.95  51.4  ... 113.17 114.21 115.9 ]
 [ 50.95  51.4   53.11 ... 114.21 115.9  116.88]]


In [14]:
len(key_seq)

7100

# 특성과 라벨을 분리 

In [15]:
import numpy as np

key_seq = np.array(key_seq)

X=key_seq[:, : -1]
y=key_seq[:, -1]

In [16]:
X_train = np.array(X)
y_train = np.array(y)

In [17]:
X_train

array([[  0.  ,   0.  ,   0.  , ...,   0.  ,   0.  ,  50.06],
       [  0.  ,   0.  ,   0.  , ...,   0.  ,  50.06,  50.89],
       [  0.  ,   0.  ,   0.  , ...,  50.06,  50.89,  51.15],
       ...,
       [  0.  ,   0.  ,  50.95, ..., 110.74, 112.23, 113.17],
       [  0.  ,  50.95,  51.4 , ..., 112.23, 113.17, 114.21],
       [ 50.95,  51.4 ,  53.11, ..., 113.17, 114.21, 115.9 ]],
      dtype=float32)

In [18]:
X_train.shape

(7100, 71)

In [19]:
X_train = X_train.reshape(7100,71,-1)

In [20]:
y_train = y_train.reshape(7100,-1)

In [21]:
X_train

array([[[  0.  ],
        [  0.  ],
        [  0.  ],
        ...,
        [  0.  ],
        [  0.  ],
        [ 50.06]],

       [[  0.  ],
        [  0.  ],
        [  0.  ],
        ...,
        [  0.  ],
        [ 50.06],
        [ 50.89]],

       [[  0.  ],
        [  0.  ],
        [  0.  ],
        ...,
        [ 50.06],
        [ 50.89],
        [ 51.15]],

       ...,

       [[  0.  ],
        [  0.  ],
        [ 50.95],
        ...,
        [110.74],
        [112.23],
        [113.17]],

       [[  0.  ],
        [ 50.95],
        [ 51.4 ],
        ...,
        [112.23],
        [113.17],
        [114.21]],

       [[ 50.95],
        [ 51.4 ],
        [ 53.11],
        ...,
        [113.17],
        [114.21],
        [115.9 ]]], dtype=float32)

In [22]:
X_train.shape

(7100, 71, 1)

In [23]:
y_train.shape

(7100, 1)

# 원 핫 인코딩  

In [24]:
#from tensorflow.keras.utils import to_categorical

#y_en = to_categorical(y, dtype='float32')

In [25]:
#y_en

# RNN예측

In [26]:
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN, LSTM
from tensorflow.keras.models import Sequential

In [27]:
X.shape

(7100, 71)

In [28]:
model = Sequential()
model.add(SimpleRNN(64,input_shape = (71,1)))
#model.add(SimpleRNN(32))
#입력 차원 지정(셀 개수 32개), 타임스텝 길이 100, 원핫인코딩 크기 100
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='relu'))
#이진분류 이므로 1개 유닛으 가짓 Dense층 추가

#model.summary() # 전체 구조 출력

In [29]:
model.compile(loss='mse',
    metrics=['mse'],)

In [30]:
history = model.fit(X_train, y_train , epochs=100)

Epoch 1/100
222/222 [==============================] - 1s 4ms/step - loss: 3601.0073 - mse: 3601.0073
Epoch 2/100
222/222 [==============================] - 1s 4ms/step - loss: 266.0491 - mse: 266.0491
Epoch 3/100
222/222 [==============================] - 1s 4ms/step - loss: 8.5716 - mse: 8.5716
Epoch 4/100
222/222 [==============================] - 1s 4ms/step - loss: 4.5572 - mse: 4.5572
Epoch 5/100
222/222 [==============================] - 1s 4ms/step - loss: 3.7238 - mse: 3.7238
Epoch 6/100
222/222 [==============================] - 1s 4ms/step - loss: 3.2193 - mse: 3.2193
Epoch 7/100
222/222 [==============================] - 1s 4ms/step - loss: 3.0221 - mse: 3.0221
Epoch 8/100
222/222 [==============================] - 1s 4ms/step - loss: 2.8048 - mse: 2.8048
Epoch 9/100
222/222 [==============================] - 1s 4ms/step - loss: 2.6923 - mse: 2.6923
Epoch 10/100
222/222 [==============================] - 1s 4ms/step - loss: 2.6073 - mse: 2.6073
Epoch 11/100
222/222 [=======

222/222 [==============================] - 1s 4ms/step - loss: 0.9744 - mse: 0.9744
Epoch 86/100
222/222 [==============================] - 1s 4ms/step - loss: 0.9380 - mse: 0.9380
Epoch 87/100
222/222 [==============================] - 1s 4ms/step - loss: 0.9285 - mse: 0.9285
Epoch 88/100
222/222 [==============================] - 1s 4ms/step - loss: 0.9070 - mse: 0.9070
Epoch 89/100
222/222 [==============================] - 1s 4ms/step - loss: 0.9458 - mse: 0.9458
Epoch 90/100
222/222 [==============================] - 1s 4ms/step - loss: 0.9132 - mse: 0.9132
Epoch 91/100
222/222 [==============================] - 1s 4ms/step - loss: 0.9396 - mse: 0.9396
Epoch 92/100
222/222 [==============================] - 1s 4ms/step - loss: 0.9129 - mse: 0.9129
Epoch 93/100
222/222 [==============================] - 1s 4ms/step - loss: 0.9268 - mse: 0.9268
Epoch 94/100
222/222 [==============================] - 1s 4ms/step - loss: 0.8960 - mse: 0.8960
Epoch 95/100
222/222 [=====================

# 예측

In [31]:
# 예측 데이터는 문제와 동일한 차원으로 입력해주어야함
model.predict([X_train[0].tolist()])

array([[50.750237]], dtype=float32)

In [32]:
a = model.predict([X_train[0].tolist()])

In [33]:
a.shape

(1, 1)

In [34]:
[[a[0].tolist()]]

[[[50.75023651123047]]]

In [35]:
b = X_train[0] + a[0].tolist()

In [36]:
b.shape

(71, 1)

In [37]:
np.concatenate([X_train[0],a])[1:].shape

(71, 1)

In [38]:
X_train[0].shape

(71, 1)

In [39]:
a.shape

(1, 1)

In [40]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [41]:
# input_height = 넘파이 배열 형식(2차원)
# n = 예측하고싶은 개월
# input_height = np.array([[50]])
def height_predict(model, input_height, n=72):
    max_len = 72
    for _ in range(len(input_height),n):# n번 반복
        encoded = pad_sequences(input_height, maxlen=max_len-1, padding='pre',dtype='float32').reshape(71,-1)
        result = model.predict([encoded.tolist()],verbose=0)
        input_height = np.hstack([input_height,result])
    return input_height

In [50]:
result = height_predict(model, np.array([[51.45]]))
result

array([[ 51.45      ,  52.0340271 ,  53.23769379,  54.30161285,
         55.25483704,  56.28380203,  57.45613861,  58.60012436,
         59.68664932,  60.73268127,  61.7739296 ,  62.86475754,
         64.01625824,  65.17589569,  66.29771423,  67.37355804,
         68.41205597,  69.42436218,  70.42198181,  71.41529846,
         72.41113281,  73.41064453,  74.40835571,  75.39285278,
         76.34938812,  77.26354218,  78.12478638,  78.92832184,
         79.67499542,  80.3698349 ,  81.02026367,  81.63469696,
         82.22164154,  82.78923035,  83.34503937,  83.89600372,
         84.44837952,  85.0078125 ,  85.57931519,  86.16743469,
         86.77645874,  87.41091919,  88.07636261,  88.78026581,
         89.53347015,  90.3524704 ,  91.26172638,  92.28948975,
         93.45381165,  94.75675201,  96.19851685,  97.78350067,
         99.50497437, 101.32579803, 103.17565918, 104.97504425,
        106.66937256, 108.24349213, 109.71190643, 111.10493469,
        112.46059418, 113.81370544, 115.

In [51]:
result[0]

array([ 51.45      ,  52.0340271 ,  53.23769379,  54.30161285,
        55.25483704,  56.28380203,  57.45613861,  58.60012436,
        59.68664932,  60.73268127,  61.7739296 ,  62.86475754,
        64.01625824,  65.17589569,  66.29771423,  67.37355804,
        68.41205597,  69.42436218,  70.42198181,  71.41529846,
        72.41113281,  73.41064453,  74.40835571,  75.39285278,
        76.34938812,  77.26354218,  78.12478638,  78.92832184,
        79.67499542,  80.3698349 ,  81.02026367,  81.63469696,
        82.22164154,  82.78923035,  83.34503937,  83.89600372,
        84.44837952,  85.0078125 ,  85.57931519,  86.16743469,
        86.77645874,  87.41091919,  88.07636261,  88.78026581,
        89.53347015,  90.3524704 ,  91.26172638,  92.28948975,
        93.45381165,  94.75675201,  96.19851685,  97.78350067,
        99.50497437, 101.32579803, 103.17565918, 104.97504425,
       106.66937256, 108.24349213, 109.71190643, 111.10493469,
       112.46059418, 113.81370544, 115.17121124, 116.47

In [48]:
model.save("Height.h5")